// <auto-generated />
using System;
using LCode.RegistroEventos.BD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LCode.RegistroEventos.BD.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210804154404_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lcode")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("LCode.NETCore.Base._5._0.Entidades.AplicativoComponente", b =>
                {
                    b.Property<int>("IdAplicativoComponente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("FechaHoraRegistro")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreComponente")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NombreComponenteCompleto")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdAplicativoComponente");

                    b.ToTable("AplicacionesComponentes");
                });

            modelBuilder.Entity("LCode.NETCore.Base._5._0.Entidades.EventoEntidad", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("EventoOrigenIdEventoOrigen")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraEvento")
                        .HasColumnType("datetime");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MensajeAdicional")
                        .HasColumnType("text");

                    b.Property<string>("MensajeDetallado")
                        .HasColumnType("text");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("int");

                    b.HasKey("IdEvento");

                    b.HasIndex("EventoOrigenIdEventoOrigen");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("LCode.NETCore.Base._5._0.Entidades.EventoOrigen", b =>
                {
                    b.Property<int>("IdEventoOrigen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AplicativoComponenteIdAplicativoComponente")
                        .HasColumnType("int");

                    b.Property<bool>("EsDocker")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraRegistro")
                        .HasColumnType("datetime");

                    b.Property<string>("IPOrigen")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("IdActividad")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NombreHost")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdEventoOrigen");

                    b.HasIndex("AplicativoComponenteIdAplicativoComponente");

                    b.ToTable("EventosOrigenes");
                });

            modelBuilder.Entity("LCode.NETCore.Base._5._0.Entidades.RastroEntidad", b =>
                {
                    b.Property<int>("IdRastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("EventoEntidadIdEvento")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraRastro")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreClase")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombreMetodo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NumeroColumna")
                        .HasColumnType("int");

                    b.Property<int>("NumeroLinea")
                        .HasColumnType("int");

                    b.HasKey("IdRastro");

                    b.HasIndex("EventoEntidadIdEvento");

                    b.ToTable("RastrosEventos");
                });

            modelBuilder.Entity("LCode.NETCore.Base._5._0.Entidades.EventoEntidad", b =>
                {
                    b.HasOne("LCode.NETCore.Base._5._0.Entidades.EventoOrigen", null)
                        .WithMany("ListaEventos")
                        .HasForeignKey("EventoOrigenIdEventoOrigen");
                });

            modelBuilder.Entity("LCode.NETCore.Base._5._0.Entidades.EventoOrigen", b =>
                {
                    b.HasOne("LCode.NETCore.Base._5._0.Entidades.AplicativoComponente", null)
                        .WithMany("ListaOrigen")
                        .HasForeignKey("AplicativoComponenteIdAplicativoComponente");
                });

            modelBuilder.Entity("LCode.NETCore.Base._5._0.Entidades.RastroEntidad", b =>
                {
                    b.HasOne("LCode.NETCore.Base._5._0.Entidades.EventoEntidad", null)
                        .WithMany("ListaRastros")
                        .HasForeignKey("EventoEntidadIdEvento");
                });

            modelBuilder.Entity("LCode.NETCore.Base._5._0.Entidades.AplicativoComponente", b =>
                {
                    b.Navigation("ListaOrigen");
                });

            modelBuilder.Entity("LCode.NETCore.Base._5._0.Entidades.EventoEntidad", b =>
                {
                    b.Navigation("ListaRastros");
                });

            modelBuilder.Entity("LCode.NETCore.Base._5._0.Entidades.EventoOrigen", b =>
                {
                    b.Navigation("ListaEventos");
                });
#pragma warning restore 612, 618
        }
    }
}
